### ISSUE TITLE
Formatting Issue - How to use - Readme.md

### ISSUE THREAD

**Issue by Rachit1313** [seog-jun/til-tool#1]
Hi,

I would like to recommend you mentioning the steps as simple text in markdown language rather than writing those as comments in bash.
Recommended Fix:
Step 1
```bash
content
```
Step 2
```bash
content
```

or you can also consider making a numbered list by starting each line with a 1. followed by a space.

Thank you.

**Comment by seog-jun** [comment]
Fixed! Thanks for your feedback!
