### ISSUE TITLE
Missing Information - Features - Readme

### ISSUE THREAD

**Issue by Rachit1313** [seog-jun/til-tool#2]
Could you please add more features in the features section in Readme.md.
For instance:
1. specific directory can be specified for the output.
2. stylesheet functionality

Mentioning all the features would make the project look more better and would be able to assist the user in knowing the functionality for getting deeper towards the code and commands.

Thank you.

**Comment by seog-jun** [comment]
Thanks for the feedback, and added more information to two functionalities!
