### ISSUE TITLE
Dependencies Issue - Package.json/Readme.md

### ISSUE THREAD

**Issue by Rachit1313** [seog-jun/til-tool#3]
Hi,
I just tried to run the code locally after downloading the zip from Github. (I didn't use git clone)

I have npm and node updated versions. Even after npm install its not able to resolve ts-node.
Could you please fix the readme.md / package.json accordingly.
![image](https://github.com/seog-jun/til-tool/assets/58596563/fc449d6b-3577-4630-8e16-16a77c38e084)

(EDIT)
Fix:
sudo npm install -g ts-node
Add this command to your readme so that the user gets ts-node installed globally. 

Thank you.

**Comment by seog-jun** [comment]
Thanks for your feedback, I updated the Readme file.
